version: '3'

services:
  app:
    image: 'patron'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3030:3030'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
